### ISSUE TITLE
FluentAssertions interface changed again - MissingMethodException

### ISSUE THREAD

**Issue by gberesford** [sandermvanvliet/SerilogSinksInMemory#2]
Having upgraded FluentAssertions to the latest version, 5.6.0, I get a MissingMethodException because the IAssertionScope changes introduced in 5.5.0 (https://github.com/fluentassertions/fluentassertions/commit/fa354f827664bd98995911e399711bb769d6e04e#diff-9ce3e8a24102d4be5af20404369fbd16L126) were reverted in 5.5.3 (https://github.com/fluentassertions/fluentassertions/commit/9a36498ac92d6cce8ae1e542233eef78b7050a7e#diff-9ce3e8a24102d4be5af20404369fbd16L95):

`Method not found: 'FluentAssertions.Execution.IAssertionScope FluentAssertions.Execution.AssertionScope.BecauseOf(System.String, System.Object[])'.
   at Serilog.Sinks.InMemory.Assertions.InMemorySinkAssertions.HaveMessage(String messageTemplate, String because, Object[] becauseArgs)`

I *think* that it should be sufficient to just rebuild the nuget package with no source code change, as it looks like you will automatically pull in and build against the latest 5.x version.

**Comment by sandermvanvliet** [comment]
I noticed it as well, thanks for letting me know. 
I'll see if I can put out a new version in the next day or so.

**Comment by sandermvanvliet** [comment]
This has been implemented in #4 and released as package version 0.3.0
